### ISSUE TITLE
Incorrect number of comments

### ISSUE THREAD

**Issue by skozlov** [yegor256/ru.yegor256.com#2]
![Снимок экрана от 2019-10-04 10-28-07](https://user-images.githubusercontent.com/3817455/66179088-d6ce4700-e691-11e9-9b78-436ef2968f44.png)
But there are comments there.

**Comment by 0crat** [comment]
@skozlov[/z](https://www.0crat.com/u/skozlov) I'm not managing this repo, remove the [webhook](https://github.com/yegor256/ru.yegor256.com/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `yegor256/ru.yegor256.com` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@skozlov it just takes some time to load them, Disqus is slow. Wait for 10-15 seconds.

**Comment by 0crat** [comment]
I'm not managing `yegor256/ru.yegor256.com` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
